### ISSUE TITLE
Typo (?)

### ISSUE THREAD

**Issue by muhdarfan** [DanishStampy/ukmads#61]
https://github.com/DanishStampy/ukmads/blob/2fa4b022b3eed87d40ecdd98cda797f0fa27ed07/resources/views/errors/404.blade.php#L15

Is it `url()->previous()` or`urL()->previous()`? (Letter L)

**Comment by MrShameer** [comment]
??

**Comment by NurfaNuva** [comment]
mampus  kau anat

**Comment by NurfaNuva** [comment]
ok done solved

**Comment by DanishStampy** [comment]
> https://github.com/DanishStampy/ukmads/blob/2fa4b022b3eed87d40ecdd98cda797f0fa27ed07/resources/views/errors/404.blade.php#L15
> 
> Is it `url()->previous()` or`urL()->previous()`? (Letter L)

it should be `url()->previous()`. Thanks for correcting the code, sir.
